# Generated by Django 2.0 on 2018-03-31 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='书籍名')),
                ('book_id', models.IntegerField(default=0, verbose_name='书籍商品id')),
                ('book_url', models.URLField(verbose_name='书籍链接')),
                ('book_price', models.IntegerField(verbose_name='书籍价格')),
            ],
            options={
                'verbose_name': '书籍名称',
                'verbose_name_plural': '书籍名称',
            },
        ),
        migrations.CreateModel(
            name='BookType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, verbose_name='书籍类型名称')),
            ],
            options={
                'verbose_name': '书籍类型',
                'verbose_name_plural': '书籍类型',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.BookType', verbose_name='书籍类型'),
        ),
    ]
